src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/sql/ddl/Person.java, src/main/java/persistence/sql/ddl/SchemaGenerator.java, src/main/java/persistence/sql/ddl/exception/NoIdentifierException.java, src/main/java/persistence/sql/ddl/mapping/PrimaryKey.java, src/main/java/persistence/sql/ddl/mapping/TableColumn.java, src/main/java/persistence/sql/dml/DmlGenerator.java, src/test/java/persistence/sql/ddl/SchemaGeneratorTest.java, src/test/java/persistence/sql/ddl/mapping/PrimaryKeyTest.java, src/test/java/persistence/sql/ddl/mapping/TableColumnTest.java, src/test/java/persistence/sql/dml/DatabaseTest.java, src/test/java/persistence/sql/dml/DmlGeneratorTest.java
=> 🚀 0단계 - 기본 코드 준비

src/main/java/domain/Person.java, src/main/java/domain/PersonNotFoundException.java, src/main/java/persistence/Application.java, src/main/java/persistence/entity/EntityKey.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/StatefulPersistenceContext.java, src/main/java/persistence/sql/dml/DmlBuilder.java, src/main/java/persistence/sql/dml/h2/H2DmlBuilder.java, src/main/java/persistence/sql/dml/h2/H2InsertQuery.java, src/main/java/persistence/sql/dml/h2/H2UpdateQuery.java, src/main/java/persistence/sql/dml/h2/H2WhereIdQuery.java, src/main/java/persistence/sql/exception/EntityIdNotFoundException.java, src/main/java/persistence/sql/exception/IllegalFieldAccessException.java, src/main/java/persistence/sql/util/ColumnCondition.java, src/main/java/persistence/sql/util/ColumnConditions.java, src/main/java/persistence/sql/util/ColumnFields.java, src/main/java/persistence/sql/util/ColumnValues.java, src/test/java/persistence/entity/EntityKeyTest.java, src/test/java/persistence/entity/StatefulPersistenceContextTest.java, src/test/java/persistence/sql/dml/h2/H2UpdateQueryTest.java, src/test/java/persistence/sql/dml/h2/H2WhereIdQueryTest.java, src/test/java/persistence/sql/util/ColumnConditionTest.java, src/test/java/persistence/sql/util/ColumnConditionsTest.java, src/test/java/persistence/sql/util/ColumnFieldsTest.java, src/test/java/persistence/sql/util/ColumnValuesTest.java
1 단계의 find, persist, remove 를 구현했습니다.
find 의 경우 값이 존재하지 않을 때 null 보다는 Optional 을 반환하는게 나을 것 같아서,
미션의 인터페이스와 다른 값을 반환하도록 했습니다.
EntityManager 는 JdbcTemplate 에 대하여 의존성을 갖는데,
이럴 때는 어떻게 테스트를 하면 좋을지 조언을 구합니다.
=> Step1 - Entity; (EntityManager 의 인터페이스 정의 및 구현) 

src/main/java/persistence/dialect/Dialect.java, src/main/java/persistence/dialect/H2DbDialect.java, src/main/java/persistence/dialect/MySqlDbDialect.java, src/main/java/persistence/dialect/collection/Dialects.java, src/main/java/persistence/dialect/collection/IdGeneratedValueStrategyMap.java, src/main/java/persistence/dialect/type/JavaToH2Type.java, src/main/java/persistence/dialect/type/JavaToMySqlType.java, src/main/java/persistence/entity/Person.java, src/main/java/persistence/sql/AbstractColumns.java, src/main/java/persistence/sql/Columns.java, src/main/java/persistence/sql/Entity.java, src/main/java/persistence/sql/EntityUtils.java, src/main/java/persistence/sql/Id.java, src/main/java/persistence/sql/IdColumns.java, src/main/java/persistence/sql/QueryBuilder.java, src/main/java/persistence/sql/ddl/DdlQueryBuilder.java, src/main/java/persistence/sql/ddl/JavaToSqlColumnParser.java, src/main/java/persistence/sql/dml/DmlQueryBuilder.java
안녕하세요 성주님!
쿼리빌더 리팩터링 하느라 조금 늦었습니다!
이번주도 파이팅입니다!!!!!
=> [step0] 0단계 - 기본 코드 준비

src/main/java/jdbc/RowMapperImpl.java, src/main/java/persistence/Application.java, src/main/java/persistence/entity/BasicEntityManger.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/sql/base/ColumnName.java, src/main/java/persistence/sql/base/ColumnNames.java, src/main/java/persistence/sql/ddl/builder/DdlQueryBuilder.java, src/main/java/persistence/sql/ddl/column/DdlColumn.java, src/main/java/persistence/sql/ddl/column/option/H2GeneratedValueStrategy.java, src/main/java/persistence/sql/dml/builder/SelectQueryBuilder.java, src/main/java/persistence/sql/dml/column/DmlColumn.java, src/test/java/fixture/PersonFixtures.java, src/test/java/persistence/entity/EntityManagerTest.java, src/test/java/persistence/sql/base/ColumnNameTest.java, src/test/java/persistence/sql/base/ColumnNamesTest.java, src/test/java/persistence/sql/dml/builder/SelectQueryBuilderTest.java, src/test/java/persistence/sql/dml/column/DmlColumnTest.java
안녕하세요~ 😄 
다음 단계에서 영속성 컨텍스트와 1차 캐시에 대해 다루기 때문에, 
그에 관련된 부분은 제외하고 엔티티 매니저를 구현하였습니다.
이전에 쿼리 빌더들을 만들어 놓아서 확실히 추가된 부분들이 많지 않네요!
이번 단계도 잘 부탁드립니다 :)
=> [Step1] 엔티티

src/main/java/persistence/Application.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/MyEntityManager.java, src/main/java/persistence/entity/Person.java, src/main/java/persistence/entity/PersonRowMapper.java, src/main/java/persistence/entity/Session.java, src/main/java/persistence/sql/Entity.java, src/main/java/persistence/sql/Id.java, src/main/java/persistence/sql/QueryBuilder.java, src/main/java/persistence/sql/ddl/DdlQueryBuilder.java, src/main/java/persistence/sql/dml/DmlQueryBuilder.java, src/test/java/persistence/entity/MyEntityManagerTest.java, src/test/java/sql/ddl/DdlQueryBuilderTest.java, src/test/java/sql/ddl/JavaToSqlColumnParserTest.java, src/test/java/sql/ddl/collection/IdGeneratedValueStrategyMapTest.java, src/test/java/sql/dml/DmlQueryBuilderTest.java
안녕하세요 성주님
요구사항 1 find 구현해 보았습니다.
이렇게 하는게 맞나 싶네요..ㅎㅎ
쿼리빌더 미션처럼 피드백 주시면 반영하면서 고도화 해보도록 하겠습니다!
고생하십니다!!
=> step1: 요구사항1 - find

src/main/java/model/Person.java, src/main/java/persistence/Application.java, src/main/java/persistence/context/BasicPersistentContext.java, src/main/java/persistence/context/PersistenceContext.java, src/main/java/persistence/entity/BasicEntityManger.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/model/Person.java, src/main/java/persistence/repository/CustomJpaRepository.java, src/main/java/persistence/sql/dml/builder/UpdateQueryBuilder.java, src/main/java/persistence/sql/dml/column/DmlColumns.java, src/main/java/persistence/sql/dml/statement/QueryStatement.java, src/main/java/util/Utils.java, src/test/java/fixture/PersonFixtures.java, src/test/java/fixture/TableFixtures.java, src/test/java/persistence/common/AccessibleFieldTest.java, src/test/java/persistence/common/FieldsTest.java, src/test/java/persistence/context/PersistenceContextTest.java, src/test/java/persistence/entity/EntityManagerTest.java, src/test/java/persistence/repository/CustomJpaRepositoryTest.java, src/test/java/persistence/sql/dml/builder/UpdateQueryBuilderTest.java
안녕하세요 ~
Step 3 에서 어떤 부분을 구현해야하나 여러 고민들을 하다보니 조금 늦어진 것 같네요! 🤔 
일단 반영된 요구사항을 구현하는데 초점을 맞추었고 피드백을 받으며 채워가겠습니다! 
잘 부탁드립니다 :)
=> [Step3] Dirty Checking

src/main/java/domain/Person.java, src/main/java/jdbc/RowMapperImpl.java, src/main/java/persistence/Application.java, src/main/java/persistence/entity/CustomJpaRepository.java, src/main/java/persistence/entity/EntityHelper.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/Persistable.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/StatefulPersistenceContext.java, src/main/java/persistence/exception/NoRowSnapshotException.java, src/main/java/persistence/exception/SnapshotCreationFailedException.java, src/test/java/persistence/entity/EntityHelperTest.java, src/test/java/persistence/entity/EntityManagerImplTest.java, src/test/java/persistence/entity/StatefulPersistenceContextTest.java
솔직히 더티체킹이 무얼 구현해야하는 건지 아직도 잘 모르겠는데,
빠르게 지적 받고 고치는게 나을 것 같아서 빠르게 PR 을 올립니다.
=> Step3: snapshot 을 통한 더티체킹 구현

build.gradle, src/main/java/persistence/Application.java, src/main/java/persistence/entity/CustomJpaRepository.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/MyEntityManager.java, src/main/java/persistence/entity/MyEntityPersister.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/Person.java, src/main/java/persistence/entity/PersonRepository.java, src/main/java/persistence/sql/Entity.java, src/main/java/persistence/sql/dml/DmlQueryBuilder.java, src/test/java/persistence/entity/MyEntityManagerTest.java, src/test/java/persistence/entity/PersonRepositoryTest.java, src/test/java/sql/dml/DmlQueryBuilderTest.java
step2 의 First Level Cache 는 피드백 반영해서 persistenceContext 에서 구현해 보았어요.
step3 에서 더티체킹 구현을 하려고 하는데.. 더티체킹 자체도 문제지만.. 트랜잭션없이 더티체킹을 어떻게 구현해야 하는건지 잘 모르겠더라구요
일단 save 메소드를 2번 호출하면서 인서트, 업데이트 순으로 쿼리가 날아갈수 있도록 구현해 보았습니다. 이게 맞는지 잘 모르겠네요.
피드백 주시면 반영하면서 고도화 해보도록 하겠습니다.
감사합니다.
=> [Step2,3] 리뷰요청 드립니다.

src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/entity/CustomJpaRepository.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/PersistenceContextImpl.java, src/main/java/persistence/entity/PersonJpaRepository.java, src/main/java/persistence/sql/dml/UpdateQueryBuilder.java, src/test/java/persistence/entity/PersistenceContextTest.java, src/test/java/persistence/entity/PersonJpaRepositoryTest.java
안녕하세요, 미션 진행이 많이 늦었습니다 😢
부족하지만 피드백을 통해서 조금씩 개선해보고자 빠르게 리뷰 요청 드렸습니다.
이번 단계도 잘 부탁 드립니다 🙇
=> [🚀 3단계 - Dirty Checking] 리뷰 요청 드립니다.

README.md, src/main/java/hibernate/ddl/CreateQueryBuilder.java, src/main/java/hibernate/ddl/DropQueryBuilder.java, src/main/java/hibernate/dml/DeleteQueryBuilder.java, src/main/java/hibernate/dml/InsertQueryBuilder.java, src/main/java/hibernate/dml/SelectAllQueryBuilder.java, src/main/java/hibernate/dml/SelectQueryBuilder.java, src/main/java/hibernate/dml/UpdateQueryBuilder.java, src/main/java/hibernate/entity/EntityClass.java, src/main/java/hibernate/entity/EntityManagerImpl.java, src/main/java/hibernate/entity/EntityPersister.java, src/main/java/hibernate/entity/EntityPersisters.java, src/main/java/hibernate/entity/EntityTableName.java, src/main/java/jdbc/JdbcTemplate.java, src/test/java/hibernate/ddl/CreateQueryBuilderTest.java, src/test/java/hibernate/ddl/DropQueryBuilderTest.java, src/test/java/hibernate/dml/DeleteQueryBuilderTest.java, src/test/java/hibernate/dml/InsertQueryBuilderTest.java, src/test/java/hibernate/dml/SelectAllQueryBuilderTest.java, src/test/java/hibernate/dml/SelectQueryBuilderTest.java, src/test/java/hibernate/dml/UpdateQueryBuilderTest.java, src/test/java/hibernate/entity/EntityClassTest.java, src/test/java/hibernate/entity/EntityManagerImplTest.java, src/test/java/hibernate/entity/EntityPersisterTest.java, src/test/java/hibernate/entity/EntityPersistersTest.java, src/test/java/hibernate/entity/EntityTableNameTest.java
안녕하세요 요한님.
큰 로직 변화없이 요구사항을 진행하였는데요. 오히려 큰 변화가 없다보니 요구사항을 제대로 이해하고 반영한것이 맞나라는 의문이 드네요. 혹시 방향성이 틀렸다면 코멘트 부탁드립니다 😢 
리뷰 잘부탁드립니다 🙇‍♂️
=> [step1] 엔터티 매핑 (EntityPersister)

src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/entity/SimpleRowMapper.java, src/main/java/persistence/exception/NoSuchEntityFoundException.java, src/main/java/persistence/sql/Query.java, src/main/java/persistence/sql/dml/UpdateQueryBuilder.java, src/test/java/persistence/entity/EntityPersisterTest.java, src/test/java/persistence/sql/dml/UpdateQueryBuilderTest.java
안녕하세요! 반갑습니다.
2주차 Entity 구현의 STEP 1 구현이 완료되어 PR 올립니다.
잘 부탁드립니다. 감사합니다!!
=> [Week 2 Entity 구현] Step 1 - 엔터티 매핑 (EntityPersister) PR

src/main/java/persistence/entity/DefaultEntityManager.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/sql/dml/ColumnValues.java, src/main/java/persistence/sql/dml/DmlQueryGenerator.java, src/main/java/persistence/sql/dml/builder/UpdateQueryBuilder.java, src/test/java/persistence/entity/DefaultEntityManagerTest.java, src/test/java/persistence/sql/dml/ColumnValuesTest.java, src/test/java/persistence/sql/dml/builder/UpdateQueryBuilderTest.java
정완님 안녕하세요!
2주차 1단계 미션 완료하여 리뷰요청 드립니다~!
EntityPersister 클래스를 정의하고 여기에 persist 관련하여 엔티티 저장, 수정, 삭제 로직을 구현하였습니다.
그 다음에는 EntityManager 클래스에서 책임을 옮겼는데요! 미션의 취지와 맞게 구현을 한 것인가 싶네요😅
EntityManager 의 find 메서드는 다음 미션에서 구현할 EntityLoader 를 통해서 처리해야 할 것 같아서 우선 TODO 로 남겨두었습니다!
여유있으실 때 한 번 봐주시면 감사하겠습니다! 남은 오후도 화이팅하세요!😄
=> step2-1) 엔터티 매핑 (EntityPersister) 리뷰요청 드립니다!

src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/impl/retrieve/EntityLoader.java, src/main/java/persistence/entity/impl/retrieve/EntityLoaderImpl.java, src/main/java/persistence/entity/impl/store/EntityPersister.java, src/main/java/persistence/entity/impl/store/EntityPersisterImpl.java, src/main/java/persistence/sql/dml/statement/UpdateStatementBuilder.java, src/test/java/persistence/entity/EntityManagerImplIntegrationTest.java, src/test/java/persistence/sql/ddl/generator/fixture/PersonV3.java, src/test/java/persistence/sql/dml/statement/UpdateStatementBuilderIntegrationTest.java, src/test/java/persistence/sql/dml/statement/UpdateStatementBuilderTest.java
=> [Week2-step1] 엔티티 매핑 리뷰 요청드립니다

src/main/java/persistence/Person.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/JdbcEntityManager.java, src/main/java/persistence/sql/Dialect.java, src/main/java/persistence/sql/H2Dialect.java, src/main/java/persistence/sql/JdbcTypeJavaClassMappings.java, src/main/java/persistence/sql/QueryBuilder.java, src/main/java/persistence/sql/SQLEscaper.java, src/main/java/persistence/sql/TableSQLMapper.java, src/main/java/persistence/sql/ddl/FieldConstraintsGenerator.java, src/main/java/persistence/sql/ddl/FieldSQLGenerator.java, src/main/java/persistence/sql/ddl/FieldStatementGenerator.java, src/main/java/persistence/sql/ddl/TableCreateQueryBuilder.java, src/main/java/persistence/sql/ddl/TableDropQueryBuilder.java, src/main/java/persistence/sql/dml/RowDeleteQueryBuilder.java, src/main/java/persistence/sql/dml/RowFindAllQueryBuilder.java, src/main/java/persistence/sql/dml/RowFindByIdQueryBuilder.java, src/main/java/persistence/sql/dml/RowInsertQueryBuilder.java
jpa-query-builder 에서 작업한 내용들을 모두 가져왔습니다.
=> step0 - 기본 코드 준비

src/main/java/persistence/entity/EntityLoader.java, src/main/java/persistence/entity/EntityManagerFactory.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/PersistenceContextImpl.java, src/main/java/persistence/exception/DuplicateContextException.java, src/main/java/persistence/exception/InvalidContextException.java, src/main/java/persistence/sql/common/instance/Values.java, src/main/java/persistence/sql/common/meta/Columns.java, src/test/java/persistence/entity/EntityManagerImplTest.java, src/test/java/persistence/entity/PersistenceContextImplTest.java
안녕하세요 정원님!
아무래도 3단계 구현해야 할 내용이 많을 것 같아서 먼저 1차 캐시 구현을 하고 PR을 올리게 되었습니다.
또 궁금했던것으로 기존 Loader가 Persister 안으로 이동하게 되었는데,
Manager에서 find 기능을 호출한다고 했을때, 
Persister에 find 메소드를 구현을 해서 그걸 부르는게 맞을지,
혹은 Manager에 Loader를 반환해서 직접 Loader의 find 관련을 호출해서 사용해주는게 맞을지가 궁금하더라구요 🤔
이번 PR도 잘 부탁드리겠습니다...!! 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️
=> [3단계] - First Level Cache 관련 구현

src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/entity/DefaultEntityManager.java, src/main/java/persistence/entity/DefaultPersistenceContext.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/repository/CustomJpaRepository.java, src/main/java/persistence/sql/meta/ColumnMetas.java, src/main/java/persistence/sql/util/ObjectUtils.java, src/test/java/persistence/entity/DefaultPersistenceContextTest.java, src/test/java/persistence/sql/meta/ColumnMetasTest.java
정완님 안녕하세요!
2주차 3단계 미션 수행하여 리뷰요청 드립니다😄
캐싱관련 내용은 크게 고민하지 않고 구현을 완료하였는데,
스냅샷과 더티체킹 관련 내용을 읽어보면서 미션수행에 좀 혼란이 있었습니다😅
현재 제 소스 구조에서는 생성한 스냅샷을 활용해서 상태별 처리로직을 구현하지는 않았는데요!
이 구현을 4단계의 엔티티엔트리를 구현하면서 수행하면 되는것인가 하여,
우선 스냅샷을 생성하고 제거하는 부분만 구현해 먼저 리뷰요청을 드리기로 했습니다😆
미션 진행에 부족한 부분이 있었다면 리뷰 따라가면서 더 보완해 보도록 하겠습니다!
그럼 이번 한 주도 화이팅하시구요! 여유있으실 때 한 번 봐주시면 감사하겠습니다😄
=> step 2-3) First Level Cache, Dirty Check 리뷰요청 드립니다!

src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/EntityPersisterCachePool.java, src/main/java/persistence/entity/JdbcEntityManager.java, src/main/java/persistence/sql/dml/UpdateDMLQueryBuilder.java, src/test/java/persistence/entity/EntityPersisterTest.java, src/test/java/persistence/entity/JdbcEntityManagerIntegrationTest.java, src/test/java/persistence/sql/dml/UpdateDMLQueryBuilderTest.java
안녕하세요 리뷰어님! 
엔터티 매핑 Step1 EntityPersister 구현하게 되어 리뷰 요청드립니다!
EntityPersister가 각 Entity class 별로 Entity의 Metadata 정보를 가지는것으로 보아, 각 Entity 별로 Persister도 인스턴스를 가지는 구조가 되는것이 바람직해보여, 요렇게 구현해 보았는데, 제가 구현한 방향이 맞는건지 고민이 되었던 스텝이었습니다.
=> [Step1] 🚀 1단계 - 엔터티 매핑 (EntityPersister)

src/main/java/persistence/entity/DefaultEntityManager.java, src/main/java/persistence/entity/DefaultPersistenceContext.java, src/main/java/persistence/entity/EntityEntry.java, src/main/java/persistence/entity/EntityKey.java, src/main/java/persistence/entity/EntityStatus.java, src/test/java/persistence/entity/DefaultPersistenceContextTest.java
정완님 안녕하세요!
4단계 EntityEntry 구현미션 수행하여 리뷰요청 드립니다!
제가 EntityEntry 개념을 잘 이해한건가 싶네요😂
엔티티 구현체와 영속상태의 묶음이라는 생각이 들어서
EntityEntry 를 엔티티 구현체와 엔티티 영속상태의 조합 클래스로 정의를 했습니다.
PersistenceContext 에서 영속화 처리 사이사이에 Entry 클래스의 상태를 변경하는 로직을 넣었습니다.
막상 이렇게 구현은 했는데... 딱히 상태정보를 확인해서 뭔가 처리하는 로직이 없으니 어색한 것 같다는 생각이 드네요😭
정완님 리뷰 받아서 방향을 잘 잡아보려고 합니다! 확인 한 번 해주시면 감사하겠습니다!
=> step 2-4) EntityEntry 리뷰요청 드립니다!

src/main/java/domain/Person.java, src/main/java/jdbc/EntityMapper.java, src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/entity/CustomJpaRepository.java, src/main/java/persistence/entity/EntityKey.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/entity/SimplePersistenceContext.java, src/main/java/persistence/entity/Snapshot.java, src/main/java/persistence/sql/QueryBuilder.java, src/main/java/persistence/sql/ddl/CreateQueryBuilder.java, src/main/java/persistence/sql/ddl/DropQueryBuilder.java, src/main/java/persistence/sql/dml/DeleteQueryBuilder.java, src/main/java/persistence/sql/dml/SelectQueryBuilder.java, src/main/java/persistence/sql/dml/UpdateQueryBuilder.java, src/main/java/persistence/sql/metadata/Column.java, src/main/java/persistence/sql/metadata/Columns.java, src/main/java/persistence/sql/metadata/EntityMetadata.java, src/test/java/persistence/entity/CustomJpaRepositoryTest.java, src/test/java/persistence/entity/SimpleEntityManagerTest.java, src/test/java/persistence/entity/SnapshotTest.java
안녕하세요 태화님...!
구조를 다 잡아놔서 이번 미션은 금방할 거라고 생각했는데..
미션 중에 제일 오래 걸렸던 것 같아요..ㅠ 늦게 나마 PR 올립니다 ㅠ
처음에는 Columns 객체를 활용해서 1차캐시와 스냅샷을 구현하려고 했는데요...!
Columns는 쿼리 빌딩을 위한 객체였던 만큼 엔티티 객체와는 성격이 다르다는 생각이 들어.. 리플렉션을 활용해서 구현했습니다.
그래서 소스가 좀 지저분하다는 생각도 드는데요 ㅠ
혹시 더 좋은 방향성이 있으면 마구마구 코멘트 부탁드립니다..! 저도 계속 고민해보겠습니다..!
=> [Step3] First Level Cache, Dirty Check

src/main/java/domain/Person.java, src/main/java/domain/Snapshot.java, src/main/java/persistence/entity/EntityLoader.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/PersistenceContextImpl.java, src/main/java/persistence/sql/common/instance/Value.java, src/main/java/persistence/sql/common/instance/Values.java, src/test/java/domain/SelectPerson.java, src/test/java/persistence/entity/EntityManagerImplTest.java, src/test/java/persistence/entity/PersistenceContextImplTest.java
정원님 안녕하세요 🥹
뒤에 더 많은 어려운 단계들이 있겠다만, 스냅샷 만들기 하다가 정말 눈물 찌이이일끔 흘린 것 같아요 ㅋ.ㅋ..ㅋ...
메타데이터를 사용하지 못하는 영속성 컨텍스트 부분에서는 어떻게 값을 비교할 것인가
메타 데이터는 이미 persister 부분에 있는데, 등등 구조부터가 잘못된건가 많은 고민을 했던 것 같아요.
저도 깊은 복사를 해야할 수 밖에 없던 경우가 있었는데, 강의 때 깊은복사까지는 하지 않아도 된다고하여
디비에서 계속 불러오는 형식으로 구현을 해 보았고, insert는 결국 바로 select를 해주기 위해서 바로 저장을 하는 형태로 구현을 했지만
update나 delete의 경우 나중에 entityManager의 flush()를 통해서 바뀐 점을 비교해서 update인지 delete인지 구분을 나름 해 주었습니다.
다들 영속성 컨텍스트랑 persister는 어쩔 수 없이 밀접 관계가 있을 수 밖에 없다고 얘기를 해주시는데
인자로 persister를 넘겨 영속성 컨텍스트 내부에서 DB 조회를 하는 모습은 아직도 낯선 것 같습니다 🥹
항상 매번 감사드립니다 ( _ _ ) 이번 PR도 잘 부탁 드리겠습니다 🙏🏻
=> [3-2단계] - Snapshot 관련 구현

README.md, src/main/java/persistence/entity/EntityEntry.java, src/main/java/persistence/entity/EntityEntryContext.java, src/main/java/persistence/entity/EntityKey.java, src/main/java/persistence/entity/EntityManagerFactory.java, src/main/java/persistence/entity/EntityPersisteContext.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/EntityStatus.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/entity/SimplePersistenceContext.java, src/main/java/persistence/exception/ObjectNotFoundException.java, src/main/java/repository/SimpleCrudRepository.java, src/test/java/persistence/entity/EntityEntryTest.java, src/test/java/persistence/entity/EntityManagerFactoryTest.java, src/test/java/persistence/entity/EntityPersisterTest.java, src/test/java/persistence/entity/EntityStatusTest.java, src/test/java/persistence/entity/SimpleEntityManagerTest.java, src/test/java/persistence/entity/SimplePersistenceContextTest.java, src/test/java/repository/RepositoryTest.java
안녕하세요 태화님
EntityEntry 구현 완료 되어 PR 올립니다.
리뷰 부탁드립니다.
=> 4단계 - EntityEntry PR

src/main/java/domain/Snapshot.java, src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/entity/EntityEntry.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/EntityPersistenceContext.java, src/main/java/persistence/entity/EntitySnapshot.java, src/main/java/persistence/entity/EntityStatus.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/PersistenceContextImpl.java, src/main/java/persistence/exception/NotFoundResultException.java, src/main/java/persistence/sql/common/meta/Column.java, src/test/java/persistence/entity/EntityManagerImplTest.java, src/test/java/persistence/entity/EntityPersisterTest.java, src/test/java/persistence/entity/PersistenceContextImplTest.java, src/test/java/persistence/sql/dml/QueryDmlTest.java
안녕하세요 정원님..! 
EntityEntry로 엔티티의 상태를 관리해줄 수 있도록 추가 하였습니다.
구현하는 중에, 점점 EntityManager의 책임이 많아진다는 생각이 들어서 작성하는 동안 이게 맞나? 진짜 맞나? 싶더라구요
하지만... EntityManager를 제외한 곳에 작성을 해주기엔 또 마땅한 영역이 없어보이기도하고...
정원님은 어떻게 생각하시는지 궁금합니다....!!
드디어 마지막 미션을 올리게 되었는데...!!
이번 PR도 잘 부탁 드리겠습니다 ( _ _ ) ~!~!
=> [4단계] - EntityEntry 구현

src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/sql/ddl/EntityMetadata.java, src/main/java/persistence/sql/dml/EntityManipulationBuilder.java, src/test/java/persistence/entity/Person.java, src/test/java/persistence/entity/SimpleEntityManagerTest.java, src/test/java/persistence/sql/ddl/EntityMetadataTest.java
=> 1단계 - 엔터티 매핑 (EntityPersister)

src/main/java/persistence/entity/EntityEntry.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/SimpleEntityEntry.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/entity/SimplePersistenceContext.java, src/main/java/persistence/entity/Status.java, src/test/java/persistence/entity/SimpleEntityManagerTest.java
안녕하세요!
EntityEntry 피드백 부탁드립니다.
EntityEntry가 어디서 어떻게 사용되는 객체인지, 어떻게 구현해야하는건지 잘 몰라서 hibernate를 참고했어요.
감사합니다.
=> [Week 2] Entity 구현 4단계 - EntityEntry

src/main/java/persistence/entity/EntityLoader.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/sql/dml/EntityManipulationBuilder.java, src/test/java/persistence/DatabaseTestBase.java, src/test/java/persistence/Fixtures.java, src/test/java/persistence/entity/EntityLoaderTest.java, src/test/java/persistence/entity/SimpleEntityManagerTest.java, src/test/java/persistence/sql/ddl/EntityMetadataTest.java, src/test/java/persistence/sql/dml/EntityManipulationBuilderTest.java
=> 2단계 - 엔터티 초기화 (EntityLoader)

src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/Person.java, src/main/java/persistence/entity/loader/EntityLoader.java, src/main/java/persistence/entity/persister/EntityPersister.java, src/main/java/persistence/sql/usecase/GetFieldFromClassUseCase.java, src/main/java/persistence/sql/usecase/SetFieldValueUseCase.java, src/test/java/persistence/PersonIntegrationTest.java, src/test/java/persistence/entity/EntityManagerTest.java, src/test/java/persistence/entity/loader/EntityLoaderTest.java, src/test/java/persistence/sql/dml/assembler/DataManipulationLanguageAssemblerH2Test.java
안녕하세요 성주님
지난번 코멘트 답변입니다.
> UseCase 가 post fix 로 붙어 있는 느낌인데요~
어떤 의미일까요?
* 클래스의 책임이 명확하게 하나가 되려면 명사가 아니라 동사형이 되는게 좋은 것 같지만 이전 리뷰에서 자바는 명사로 쓰는걸 권장한다는 내용이 있어서 UseCase 를 붙이게 되었습니다.
> else 를 제거해보면 어떨까요~?
* EntityManagerImpl 의 persist 에 수정이 어느정도 되었습니다.
> 사용하지 않는 import 는 정리하면 좋을 것 같아요~
rowMapper 가 사용되는 곳이 없는 것 같은데요~ 사용하지 않는다면 제거해 보는 것이 어떨까요?
* 제거했습니다.
>별건 아니지만! 로직을 보다가 우연히 발견하게 되어서 코멘트 달아보아요!
GetFieldFromClassUseCase 에서 로직을 메서드로 분리해보면 더욱 가시성이 좋아질 것 같아요!
* GetFieldFromClassUseCase 의 메서드에서 리플렉션 Field 를 DatabaseField 로 변환하는 메소드를 만들었습니다.
현재 구현에 대한 설명을 하면
EntityManager 가 EntityLoader, EntityPersister 를 각각 가지고 있는데 이렇게 되면 jdbc template 이 하나인 경우엔 괜찮겠지만 멀티 데이터소스가 되면 아래와 같이 될 것 같습니다.
만약 한 스레드에서 두 개의 데이터 소스를 각각 필요하게 된다면
dataSource 1 -> entityManager 1
dataSource 2 -> entityManager 2
이렇게 dataSource마다 …
=> Step2 - 엔터티 초기화 (EntityLoader)

src/main/java/persistence/entity/CustomJpaRepository.java, src/main/java/persistence/entity/EntityLoader.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/entity/SimplePersistenceContext.java, src/main/java/persistence/sql/ddl/EntityDefinitionBuilder.java, src/main/java/persistence/sql/ddl/EntityMetadata.java, src/main/java/persistence/sql/ddl/FieldMetadataExtractor.java, src/main/java/persistence/sql/ddl/FieldMetadataExtractors.java, src/main/java/persistence/sql/dml/DataLanguage.java, src/main/java/persistence/sql/dml/EntityManipulationBuilder.java, src/main/java/utils/CustomStringBuilder.java, src/test/java/persistence/DatabaseTestBase.java, src/test/java/persistence/entity/CustomJpaRepositoryTest.java, src/test/java/persistence/entity/Person.java, src/test/java/persistence/entity/SimpleEntityManagerTest.java, src/test/java/persistence/entity/SimplePersistenceContextTest.java, src/test/java/persistence/sql/ddl/EntityDefinitionBuilderTest.java, src/test/java/persistence/sql/ddl/EntityMetadataTest.java, src/test/java/persistence/sql/dml/EntityManipulationBuilderTest.java
=> 3단계 - First Level Cache, Dirty Check

build.gradle, src/main/java/persistence/entity/EntityEntries.java, src/main/java/persistence/entity/EntityEntry.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/entity/SimplePersistenceContext.java, src/main/java/persistence/entity/Status.java, src/main/java/persistence/sql/ddl/EntityMetadata.java, src/main/java/persistence/sql/ddl/FieldMetadataExtractor.java, src/main/java/persistence/sql/ddl/FieldMetadataExtractors.java, src/main/java/utils/ReflectionUtils.java, src/test/java/persistence/DatabaseTestBase.java, src/test/java/persistence/entity/EntityEntriesTest.java, src/test/java/persistence/entity/EntityPersisterTest.java, src/test/java/persistence/entity/Person.java, src/test/java/persistence/entity/SimpleEntityManagerTest.java, src/test/java/persistence/entity/SimplePersistenceContextTest.java
=> 4단계 - EntityEntry

README.md, src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/Application.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/MyEntityManager.java, src/main/java/persistence/entity/MyEntityPersister.java, src/main/java/persistence/sql/dml/UpdateQueryBuilder.java, src/test/java/persistence/entity/EntityPersisterTest.java, src/test/java/persistence/entity/MyEntityPersisterTest.java, src/test/java/persistence/sql/dml/UpdateQueryBuilderTest.java
안녕하세요 정원님, ☺️
이번 미션에서는 UpdateQueryBuilder를 만드는 작업 말고는 큰 작업은 없었습니다.
>  요구사항 2번 - EntityManager 의 구현체에서 쿼리 생성 및 데이터 매핑 에 대한 책임을 EntityPersister 로 옮겨주자
만족시키려면 추후 `EntityLoader` 가 생성된 뒤에 데이터 매핑 부분을 넘겨줄 수 있을 것 같습니다.
리뷰 잘 부탁드립니다!🙇🏻‍♂️
=> [Step1 - 엔터티 매핑 (EntityPersister)] 김현태 미션 제출합니다.

README.md, src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/MyEntityManager.java, src/main/java/persistence/entity/MyEntityPersister.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/persistencecontext/EntityKey.java, src/main/java/persistence/persistencecontext/EntitySnapshot.java, src/main/java/persistence/persistencecontext/MyPersistenceContext.java, src/main/java/persistence/persistencecontext/PersistenceContext.java, src/main/java/persistence/sql/Person.java, src/main/java/persistence/sql/dml/InsertQueryBuilder.java, src/main/java/persistence/sql/dml/UpdateQueryBuilder.java, src/main/java/persistence/sql/domain/Table.java, src/main/java/repository/CustomJpaRepository.java, src/main/java/repository/JpaRepository.java, src/main/java/utils/ValueExtractor.java, src/main/java/utils/ValueInjector.java, src/test/java/persistence/entity/MyPersistenceContextTest.java, src/test/java/persistence/persistencecontext/MyPersistenceContextTest.java, src/test/java/repository/CustomJpaRepositoryTest.java
안녕하세요 정원님,
갑자기 3단계 때 난이도가 훅 올라간 것 같네요...
2번 요구사항을 정확하게 파악을 하기 어려워서, 3번을 먼저 진행하면서 필요한 부분들을 만들어봤습니다.
CustomJPARepository를 통해서 save를 구현해보려고 하니 2가지 케이스에 대해서 찾아야하더라구요.
1. 영속화되지 않은 엔티티
- entityManger.persist()
2. 영속화된 엔티티
- entityManager.merge()
JPA를 찾아보니 id 값이 null 인 경우 new로 바라보고 처리하는 것 같은데,
제가 현재 설계한 구조에서는 `Table` 로 만들 때 객체에서 사용하고 있던 field값을 그대로 가져와서 저장하기 때문에 걸러지지가 않더라구요.
우선 테스트 코드에서는 null인 상황을 가정하고 구현했는데 해당 부분을 어떻게 하면 좋을지 도와주세요!
제가 미션을 잘 이해하고 진행한지는 잘 모르겠는데,
우선 제가 생각하는 1차 캐시와 더티 체킹의 느낌으로 구현해봤습니다.
이번 단계도 잘 부탁드립니다!
=> [Step3 - First Level Cache, Dirty Check] 김현태 미션 제출합니다.

src/main/java/database/sql/dml/ColumnValueMap.java, src/main/java/database/sql/dml/QueryBuilder.java, src/main/java/database/sql/dml/UpdateQueryBuilder.java, src/main/java/persistence/Application.java, src/main/java/persistence/entity/EntityLoader.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/EntitySnapshot.java, src/main/java/persistence/entity/EntitySnapshotDifference.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/PersistenceContextImpl.java, src/test/java/database/sql/dml/DeleteQueryBuilderTest.java, src/test/java/database/sql/dml/UpdateQueryBuilderTest.java, src/test/java/persistence/entity/EntityLoaderTest.java, src/test/java/persistence/entity/EntityManagerImplTest.java, src/test/java/persistence/entity/EntityPersisterTest.java, src/test/java/persistence/entity/EntitySnapshotDifferenceTest.java, src/test/java/persistence/entity/EntitySnapshotTest.java, src/test/java/persistence/entity/PersistenceContextImplTest.java, src/test/java/testsupport/EntityTestUtils.java, src/test/java/testsupport/H2DatabaseTest.java, src/test/java/testsupport/LoggingJdbcTemplate.java, src/test/java/testsupport/MyJdbcTemplate.java
안녕하세요, 태화님!
이번 단계는 방황을 많이 해서, 커밋을 잘 정리하지 못해 결국 한덩어리로 올리게 되었습니다.
변경도 꽤 많아서, 특이할만한 부분은 코멘트를 달아 두어 보겠습니다.
이번에도 잘 부탁드립니다. :)
=> 🚀 3단계 - First Level Cache, Dirty Check

README.md, src/main/java/persistence/Person.java, src/main/java/persistence/entity/EntityMangerImpl.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/GeneratedIdObtainStrategy.java, src/main/java/persistence/entity/H2GeneratedIdObtainStrategy.java, src/main/java/persistence/sql/dml/UpdateQueryBuilder.java, src/main/java/persistence/sql/mapping/Columns.java, src/test/java/persistence/H2DBTestSupport.java, src/test/java/persistence/entity/EntityMangerImplTest.java, src/test/java/persistence/entity/EntityPersisterTest.java, src/test/java/persistence/sql/dml/UpdateQueryBuilderTest.java, src/test/java/persistence/sql/mapping/ColumnsTest.java
안녕하세요 기륭님, 
```
public class EntityPersister {
- 구현 해보기
// e.g 
// private EntityName entityName;
// private EntityTableName entityTableName;
// private EntityCoulmns entityCoulmns;
// private EntityValues entityValues;
// .... 등
```
여기서 Persister가 특정 엔티티의 상태를 가지고 있는게 잘 이해가 안가는데 
EntityManager가 여러개의 EntityPersister를 가지고 있거나 매번 만들라는 의도일까요? 
지금은 하나만 쓰고 요청마다 ColumnData 같은 매핑정보를 새로 만들게 해뒀습니다.
잘부탁드립니다!
=> Step1 - 엔터티 매핑

src/main/java/persistence/Application.java, src/main/java/persistence/entity/EntityEntry.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityMeta.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/EntityStatus.java, src/main/java/persistence/entity/MyEntityManager.java, src/main/java/persistence/entity/MyEntityPersister.java, src/main/java/persistence/persistencecontext/MyPersistenceContext.java, src/main/java/persistence/persistencecontext/PersistenceContext.java, src/main/java/persistence/sql/domain/Table.java, src/main/java/repository/CustomJpaRepository.java, src/test/java/persistence/entity/MyEntityManagerTest.java, src/test/java/persistence/entity/MyEntityPersisterTest.java, src/test/java/persistence/persistencecontext/MyPersistenceContextTest.java
안녕하세요 정원님,
4단계 EntityEntry 엔터티 상태 추가하기 미션을 진행해봤습니다.
남겨주신 커멘트를 도움받아 `EntityMeta` 클래스를 추가하니 구조가 훨씬 파악하기 쉽게 바뀐 것 같습니다.
미션을 진행하면서 점점 하이버네이트에 대한 이해도가 올라가고 있음을 느낍니다👍🏻
말씀해주신 것처럼 Transaction과 항상 같이 써오다가 없이쓰니 의문이 들었던 것 같습니다.
좋은 피드백 감사합니다ㅎㅎ
추가로 남겨주신 `flush()` 를 어떻게 구현해야할지도 계속 고민해보겠습니다.
먼저 PR을 올려놓고 피드백을 받으면서, 생각이 나는데로 해당 PR 건에 flush 내용에 대해서 추가하도록 하겠습니다.
---
여전히 조금 해결이 안된 고민이 있는데요,
save()할 때 persist, merge 분기처리를 하기 위한 `isNew()` 메서드 구현에서 헷갈립니다.
엔티티가 새로운 엔티티인지, DB에 존재하는 엔티티인지 확인하는 메서드를 구현하기가 어렵습니다.
뭔가 EntityEntry를 만들면 처리할 수 있을까 했는데, PersistenceContext 안에서 관리를 하다보니 접근하기가 어렵습니다.
입력된 Entity의 ID 값의 유무에 따라 구분하기에는 사용자가 입력한 ID 값이 있으면 또 판단할 수가 없겠더라구요.
그러면 1) 1차 캐시에 존재하는지 확인 2) DB의 generatedKey 를 통해 확인 이런 절차를 거쳐야할 것 같은데
2)의 경우 select 쿼리까지 발생하게되니 이렇게 사용하지는 않을 것 같고, 1번처럼 캐시에 접근할 수 있는 수단이 존재해야 하는건가요?
=> [Step4 - EntityEntry] 김현태 미션 제출합니다.

src/main/java/domain/Constraints.java, src/main/java/domain/EntityMetaData.java, src/main/java/domain/H2GenerationType.java, src/main/java/domain/Person1.java, src/main/java/domain/Person2.java, src/main/java/domain/Person3.java, src/main/java/domain/constants/CommonConstants.java, src/main/java/domain/dialect/Dialect.java, src/main/java/domain/dialect/H2Dialect.java, src/main/java/domain/utils/StringUtils.java, src/main/java/domain/vo/ColumnName.java, src/main/java/domain/vo/ColumnValue.java, src/main/java/domain/vo/JavaMappingType.java, src/main/java/jdbc/JdbcTemplate.java, src/main/java/jdbc/RowMapperImpl.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/sql/ddl/DdlQueryBuilder.java, src/main/java/persistence/sql/dml/DmlQueryBuilder.java
안녕하세요!
이전 미션 코드 이관한 뒤 pr 요청드립니다.
=> [Entity 구현 - Step 0단계] 기본 코드 준비

README.md, src/main/java/persistence/entity/CustomJpaRepository.java, src/main/java/persistence/entity/EntityEntry.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/entity/persistencecontext/PersistenceContext.java, src/main/java/persistence/entity/persistencecontext/SimplePersistenceContext.java, src/test/java/persistence/entity/persistencecontext/SimplePersistenceContextTest.java
안녕하세요 리뷰어님 4단계 리뷰 요청드립니다.
status의 변경을 manager에서 해야되는지 persistenceContext에서 해야될지 고민이 됩니다.
어떻게 처리하셨을까요?
=> 🚀 4단계 - EntityEntry

README.md, src/main/java/persistence/entity/EntityEntry.java, src/main/java/persistence/entity/EntityEntryContext.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/EntityStatus.java, src/main/java/persistence/entity/PersistenceContext.java, src/main/java/persistence/entity/PersistenceContextImpl.java, src/main/java/persistence/entity/SimpleEntityEntry.java, src/main/java/persistence/entity/exception/ObjectNotFoundException.java, src/test/java/persistence/entity/EntityEntryContextTest.java, src/test/java/persistence/entity/EntityManagerImplTest.java, src/test/java/persistence/entity/PersistenceContextImplTest.java
안녕하세요 요한 리뷰어님!
매번 리뷰 꼼꼼히 해주셔서 감사합니다~
step4 미션 코드리뷰요청드립니다 🙇🏻 
`EntityEntry` 의 상태값 정보를 어디에 보관할것인가? 에 대해 고민이 많았는데, 
Entity의 상태값을 관리하기 위함이니 1차 캐시, 스냅샷저장소와 목적이 다른것 같아 
별도로 `EntityEntryContext`로 분리하여 관리하였습니다!
=>  4단계 - EntityEntry

README.md, src/main/java/persistence/entity/EntityLoader.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/sql/metadata/EntityMetadata.java, src/main/java/persistence/sql/metadata/PrimaryKeyMetadata.java, src/test/java/persistence/entity/SimpleEntityManagerTest.java
정원님 step1의 빠른리뷰 감사합니다.
정신없이 진행하다보니 놓친 포인트가 몇가지 있는 것 같아 여쭤보려고합니다.
1. EntityRowMapper 관련
* `Class<T>`로 활용한 부분이 어색하여, Metadata를 구현해놓은 게 있어서 활용하면 좋을 것 같은데, 어떻게 리팩터링해야 좋을지 고민이되네요.
* 혹시 좋은 의견 있으시면 힌트를 얻고자 합니다.
2. `EntityLoader` 의 `findByEntity` 에서 `(Class<T>) entity.getClass()` 를 가져오는 과정에서, Unchecked cast 가 발생하고 있는데, 혹시 다른 대안이 있을까요?
=> 🚀 2단계 - 엔터티 초기화 (EntityLoader)

src/main/java/database/H2.java, src/main/java/persistence/Application.java, src/main/java/persistence/entity/EntityLoader.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityPersister.java, src/main/java/persistence/entity/impl/EntityLoaderImpl.java, src/main/java/persistence/entity/impl/EntityManagerImpl.java, src/main/java/persistence/entity/impl/EntityPersisterImpl.java, src/main/java/persistence/exception/ReflectionRuntimeException.java, src/main/java/persistence/sql/EntityColumn.java, src/main/java/persistence/sql/EntityColumnValue.java, src/main/java/persistence/sql/EntityColumnValues.java, src/main/java/persistence/sql/EntityColumns.java, src/main/java/persistence/sql/EntityTable.java, src/main/java/persistence/sql/Metadata.java, src/main/java/persistence/sql/QueryBuilder.java, src/main/java/persistence/sql/dml/UpdateQueryBuilder.java, src/test/java/persistence/entity/impl/AbstractJdbcTemplateTest.java, src/test/java/persistence/entity/impl/EntityManagerImplTest.java, src/test/java/persistence/entity/impl/EntityPersisterImplTest.java, src/test/java/persistence/sql/EntityColumnValueTest.java, src/test/java/persistence/sql/EntityColumnValuesTest.java, src/test/java/persistence/sql/EntityColumnsTest.java, src/test/java/persistence/sql/EntityTableTest.java, src/test/java/persistence/sql/MetadataTest.java, src/test/java/persistence/sql/ddl/query/QueryBuilderTest.java
- [feat: Metadata 구현](https://github.com/next-step/jpa-entity-manager/commit/59944f8ec69856bbacc6f692f0feb8b8b6dd77a0)
- [feat: 요구사항 1 - 엔터티의 데이터베이스 매핑, 쿼리 생성 및 실행](https://github.com/next-step/jpa-entity-manager/commit/26a1d1337cf72222a3d4a20d010ad6990c359afa)
- [feat: 요구사항 2 - EntityManager 의 책임 줄여주기](https://github.com/next-step/jpa-entity-manager/commit/bbaf6b9b681b52a59170b509a4ff74cab5e7041c)
=> feat: 1단계 - 엔터티 매핑 (EntityPersister)

build.gradle, src/main/java/persistence/sql/EntityColumns.java, src/main/java/persistence/sql/dml/UpdateQueryBuilder.java, src/test/java/persistence/entity/EntityRowMapperFactoryTest.java, src/test/java/persistence/entity/impl/EntityLoaderImplTest.java
- [feat: code-review 반영](https://github.com/next-step/jpa-entity-manager/commit/841647c542f5eaf94192a23e1b94212ef6999a6a)
- [feat: 2단계 - 엔터티 초기화 (EntityLoader)](https://github.com/next-step/jpa-entity-manager/commit/af4b9fc89e75f2f056ebd1c66512a65c64d7f5c5)
=> feat: 2단계 - 엔터티 초기화 (EntityLoader)
